### ISSUE TITLE
CSRF issue

### ISSUE THREAD

**Issue by amazium** [samsonasik/mezzio-authentication-with-authorization#14]
The CSRF is giving me an issue on mac os x, php 7.4.

"The form submitted did not originate from the expected site"

As far as I can tell, it is a problem with the session and how the csrf is stored. Somehow it looks as if it is recalculated after submitting.

**Comment by samsonasik** [comment]
I'm using mac os x as well, php 7.4 and I can't reproduce it.  Please check your php.ini session save path. Also, please try to save the session to different location, eg: in `public/index.php`, temporary, set: 

```php
ini_set('session.save_path', './data');
```

**Comment by amazium** [comment]
Apparently it is a chrome issue. curl and firefox did not do it. Unrelated to your project.

I noticed the php built in webserver executed all requests twice. After some research it turns out that the php built in webserver is too slow causing chrome to fire a second request. This causes the session to be updated with a new token.

You can close this issue.
