### ISSUE TITLE
Adding new user & role using MySQL

### ISSUE THREAD

**Issue by dennis-fedco** [samsonasik/mezzio-authentication-with-authorization#15]
Hello

I am using MySQL for password and user storage.  Could you please tell me how to create new passwords using MySQL when I have a new username and role in mind?  I don't see a clear way towards doing so, and looking through code so far has me confused.  Thanks!

**Comment by goharsahi** [comment]
@dennis-fedco try SET password = ENCRYPT('<SOME_PASSWORD>') .

Hope this works.

**Comment by samsonasik** [comment]
The default one is configuration based, it may custom code to load roles from DB. Pull request is welcome.

**Comment by dennis-fedco** [comment]
Thank you!  Encrypt appears to be deprecated in later MySQL versions.  I am looking into more details.  There may be a better method for MySQL for this purpose.  I will consider a PR as more info is known.
