### ISSUE TITLE
How to incorporate it in the ongoing project?

### ISSUE THREAD

**Issue by goharsahi** [samsonasik/mezzio-authentication-with-authorization#17]
From what I see, the only option there is to use it from the scratch. Can we not have the option of adding it in the ongoing project, like quite a few other packages?

Also, it is lacking the schema.sql which will be good to have.

**Comment by samsonasik** [comment]
It may need to be extracted to modules, but not sure if I have a time to do it in the near future

**Comment by samsonasik** [comment]
Closing as I don't have time to extract into modules right now.
