### ISSUE TITLE
How can I use this app for multiple granular in-view authorization queries?

### ISSUE THREAD

**Issue by dennis-fedco** [samsonasik/mezzio-authentication-with-authorization#18]
Question - it seems that I can use authorization on a per-view-template level.

However, I have a use case to evaluate authorization on a more granular level.
For example, I have a module called `Quote` and in that module I have a `quote` view that shows a listing of sales items without their prices for customer view, but I want to show pricing for a sales person viewing the same quote view.

And so I am looking for a model where I can use something like this:

    if ("logged in user" has permission to "view sales line item pricing")
        echo $price;
    else
        echo "";

Where I can have multiple such statements on a single view.
It is not immediately clear if I can modify the app to use it in such a granular way.

Can I use `mezzio-authentication-with-authorization` for my use case?  If so, how?
If I wanted to write a lot of such statements, how can I use (modify) this app?
Thanks!

**Comment by samsonasik** [comment]
There is `isGranted` view helper for that:

https://github.com/samsonasik/mezzio-authentication-with-authorization/blob/dcf300d89fa38248a21ca96266d50a847653e91e/templates/layout/default.phtml#L57

**Comment by dennis-fedco** [comment]
I understand that `admin.view` is linked to a specific single route.

In my case I need multiple authorization statements inside the route.

For example, inside the template of the admin Handler I want the user to only see the products that they are allowed to view.  I might thus do something like this:

    if ($this->isGranted('admin.view.productA')) echo "can view product A";
    if ($this->isGranted('admin.view.productB')) echo "can view product B";
    ....
    if ($this->isGranted('admin.view.productZ')) echo "can view product C";

Would I need to set up a route & handler for each product line?

**Comment by samsonasik** [comment]
resource is nothing todo with routes, it is place that role can access, see example in layout that nothing todo with routing:

https://github.com/samsonasik/mezzio-authentication-with-authorization/blob/dcf300d89fa38248a21ca96266d50a847653e91e/templates/layout/default.phtml#L57-L63
 
Your example like different roles, You need a different roles definition. 

if the roles are many, you probably need to load from DB, and generate configuration authorization via middleware into re-set `config` service.

**Comment by dennis-fedco** [comment]
In my case if I add a resource called `arbitrary_resource` in config, like so:

    'mezzio-authorization-acl' => [
        'resources' => [
            'arbitrary_resource'
        ],
        'allow' => [
            'admin' => [
                'arbitrary_resource'
            ]
        ]
    ],

And then in the Admin template add this code:

    <?php // templates/app/admin-page.phtml ?>
    Admin Page
    
    <?php if ($this->isGranted('arbitrary_resource')) :?>
    Access to Arbitrary Resource GRANTED
    <?php else : ?>
    Access to Arbitrary Resource DENIED
    <?php endif; ?>

I get the error
 
    Mezzio \ Router \ Exception \ RuntimeException:  Cannot generate URI for route "arbitrary_resource"; route not found

Why is it trying to create a route out of my `arbitrary_resource`?

**Comment by samsonasik** [comment]
Oh, just re-checked the `IsGranted` view helper that it check the URI for it:

https://github.com/samsonasik/mezzio-authentication-with-authorization/blob/dcf300d89fa38248a21ca96266d50a847653e91e/src/App/View/Helper/IsGranted.php#L30-L33

You may need to create custom Acl instance, not from `Mezzio\Authorization\Acl\Acl` ,but from `Laminas\Permissions\Acl\Acl`.

https://docs.laminas.dev/laminas-permissions-acl/ so you can define resource not as a route, just a name.

**Comment by dennis-fedco** [comment]
Thanks

To clarify, instead of using `LaminasAcl` which implements `Mezzio\Authorization\AuthorizationInterface`
I will need to create a `CustomAcl` that implements `Laminas\Permissions\Acl\AclInterface`

Does that look correct?

**Comment by samsonasik** [comment]
You should can use the `Acl` instance https://github.com/laminas/laminas-permissions-acl/blob/2.9.x/src/Acl.php

https://docs.laminas.dev/laminas-permissions-acl/refining/

**Comment by dennis-fedco** [comment]
Thanks, but I am sorry, I am not clear on where that `Acl` should be instantiated

**Comment by samsonasik** [comment]
You can create service for that. There is no strict way to do that as you will create a custom for it.
