### ISSUE TITLE
Is there a way to use native ACL inside templates?

### ISSUE THREAD

**Issue by dennis-fedco** [samsonasik/mezzio-authentication-with-authorization#19]
I want to use native ACL inside templates.  

For example, inside a view template, something like:

    $auth->isAllowed($role, $resource));
    $this->isAllowed($role, $resource));

Is there an easy way to modify this app to do so?  How?

**Comment by samsonasik** [comment]
Role is based on logged in user. Why you need to pass role in a view ? There is `isGranted()` view helper for inspiration

https://github.com/samsonasik/mezzio-authentication-with-authorization/blob/dcf300d89fa38248a21ca96266d50a847653e91e/src/App/View/Helper/IsGranted.php#L30

https://github.com/samsonasik/mezzio-authentication-with-authorization/blob/dcf300d89fa38248a21ca96266d50a847653e91e/templates/layout/default.phtml#L57

**Comment by samsonasik** [comment]
Closing as duplicated with https://github.com/samsonasik/mezzio-authentication-with-authorization/issues/18
