### ISSUE TITLE
For the valid /login route, why does the app execute middleware placed after the DispatchMiddleware in the pipeline?

### ISSUE THREAD

**Issue by dennis-fedco** [samsonasik/mezzio-authentication-with-authorization#21]
I am experiencing an issue where I think the app may be behaving incorrectly, or maybe there is a special routing issue happening that I am not considering.

My belief is that if I hit a valid route, such as `/login` with the app, the pipeline should _never_ go past `DispatchMiddleware.php`, and any middleware placed afterwards should not be executed.  In my case, `/login` route goes past `DispatchMiddleware.php`, executing my custom middleware and I want to understand why.

**To duplicate the behavior I am experiencing:**
* Create `src/App/Middleware/LegacyApplicationMiddleware.php` with code below:

    declare(strict_types = 1);
    namespace App\Middleware;
    
    use Psr\Http\Message\ResponseInterface;
    use Psr\Http\Message\ServerRequestInterface;
    use Psr\Http\Server\MiddlewareInterface;
    use Psr\Http\Server\RequestHandlerInterface;
    
    class LegacyApplicationMiddleware implements MiddlewareInterface
    {
        public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
        {
            die("why do we get here?");
        }
    }

* Place the new middleware after DispatchMiddleware:

    $app->pipe(DispatchMiddleware::class);
    $app->pipe(LegacyApplicationMiddleware::class);

* Place new middleware into config under `'factories'` key:
    

    LegacyApplicationMiddleware::class => InvokableFactory::class

* Run the app and attempt to log in using any valid username and password

**Expectation** 
After logging in, you should be able to see the default "Welcome to mezzio" login page with the message on top stating "You are succesfully authenticated"

**Actual behavior** 
After login attempt, instead of the welcome page, you see the message "why do we get here?", because `LegacyApplicationMiddleware` is being executed after the `DispatchMiddleware`, despite `/login` being a valid route. My understanding is that a legal route should be entirely serviced by the `DispatchMiddleware` and go no further than that in the execution of the `pipeline.php` 

Why is my middleware being executed?  The intent of my middleware is to only work when I try to load a route that has not been specified in my config, that normally would result in 404 Not Found error.  In this case, `/login` route is found, and should not result in 404 error.  I say 404 error, because normally `NotFoundHandler` will be executed after `DispatchMiddleware`.  In my case, `LegacyApplicationMiddleware` is being executed first

Can you help explain what's going on?  Is that a quirk of the `/login` route specifically? Is it a malfunction/discrepancy of the `mezzio-authentication-with-authorization`? Something else?

**Comment by samsonasik** [comment]
that's executed as ordered in the pipeline, if you want to protect the middleware by session, you can check with session check:

https://github.com/samsonasik/mezzio-authentication-with-authorization/blob/b67ea96c4e5079142a4b129e27576f1657fcd1f7/src/App/Middleware/UserMiddleware.php#L34

or register by route:

https://github.com/samsonasik/mezzio-authentication-with-authorization/blob/b67ea96c4e5079142a4b129e27576f1657fcd1f7/config/routes.php#L69

**Comment by dennis-fedco** [comment]
Hi, thank you but I don't think I understand. 

If I remove my `LegacyApplicationMiddleware` from the pipeline, I can trace the code execution going into and executing code in `$app->pipe(NotFoundHandler::class);` for the `/login` route.   Is that the expected behavior of the pipeline?   If so, why?  The `/login` route _is_ found, so why does code execution reach and go into `NotFoundHandler` middleware when the route is found?

Also, I do not understand what you said about protecting the middleware. LegacyApplicationMiddleware`, right?  Protecting it from what, and why?  What do SessionMiddleware or PrgMiddleware do exactly?  Sorry, I don't think I am seeing the bigger picture.

My goal is to have my code in `LegacyApplicationMiddleware` execute only when reaching an invalid Mezzio route, so I can tie in and run my legacy code.  My expectation was that using `/login` route will only reach the `DispatchMiddleware` and not reach my `LegacyApplicationMiddleware` nor into the `NotFoundHandler` but it does....

**Comment by dennis-fedco** [comment]
I note that class `LoginPageHandler` implements `MiddlewareInterface`, so it is not a request handler but rather a middleware.  This makes it a bit more clear to me why the pipeline keeps executing past the `DispatchMiddleware` instead of going back.
I'm still looking into `LoginPageHandler` to understand it better.

**Comment by dennis-fedco** [comment]
Looking further into the `LoginPageHandler`, it looks to me like this line on [LoginPageHandler.php#L42](https://github.com/samsonasik/mezzio-authentication-with-authorization/blob/b67ea96c4e5079142a4b129e27576f1657fcd1f7/src/App/Handler/LoginPageHandler.php#L42) is the one responsible for allowing requests to "fall through" the pipeline, past the `DispatchMiddleware`, and onwards to the `NotFoundHandler` middleware. 

Code execution of that `LoginPageHandler.php#L42` line then returns with either a `404` HTTP status code, which means user was successfully authenticated, or a `302` code, which means user was not authenticated.

Is there a different way to log in and authenticate a user without having requests going through the entire pipeline past the `DispatchMiddleware` and to where a 404 status code is issued?

**Comment by samsonasik** [comment]
The LoginPageHandler uses AuthenticationMiddleware next to verify request data:

https://github.com/samsonasik/mezzio-authentication-with-authorization/blob/b67ea96c4e5079142a4b129e27576f1657fcd1f7/config/routes.php#L73

Feel free to create failing unit test case if you found a bug, thank you.

**Comment by dennis-fedco** [comment]
I've created a pull request that showcases my use case.  There are two existing tests on Login Page (`AppTest\Integration\LoginPage`) that fail based on my use case.
